Repository marineks/Ft_irc, pull requests merged in 2023-01, with the labels that each got.

#19 Cmd parsing
  .gitignore
  .vscode/settings.json
  Makefile
  includes/Channel.hpp
  includes/Commands.hpp
  includes/Irc.hpp
  includes/Server.hpp
  srcs/Channel.cpp
  srcs/ManageServer.cpp
  srcs/Server.cpp
  srcs/commands/invite.cpp
  srcs/commands/join.cpp
  srcs/commands/kick.cpp
  srcs/commands/ping.cpp
  srcs/commands/topic.cpp
  srcs/parsing.cpp
Labels: enhancement

#20 List command implemented
  Makefile
  includes/Channel.hpp
  includes/Commands.hpp
  srcs/Channel.cpp
  srcs/Server.cpp
  srcs/commands/list.cpp
Labels: enhancement

#21 Invite cmd
  Makefile
  includes/Commands.hpp
  includes/Server.hpp
  srcs/Server.cpp
  srcs/commands/invite.cpp
  srcs/commands/topic.cpp
  srcs/parsing.cpp
Labels: enhancement

#22 Nick cmd
  Makefile
  includes/Client.hpp
  includes/Commands.hpp
  includes/Server.hpp
  srcs/Client.cpp
  srcs/Server.cpp
  srcs/commands/invite.cpp
  srcs/commands/nick.cpp
Labels: enhancement

#23 Numerical rpl
  Makefile
  includes/Irc.hpp
  includes/Numerical_replies.hpp
  srcs/commands/invite.cpp
  srcs/commands/nick.cpp
  srcs/commands/topic.cpp
  srcs/utils.cpp
Labels: enhancement

#25 Mdp command
  Makefile
  includes/Client.hpp
  includes/Commands.hpp
  includes/Numerical_replies.hpp
  includes/Server.hpp
  srcs/Client.cpp
  srcs/Server.cpp
  srcs/commands/pass.cpp
  srcs/main.cpp
Labels: enhancement

#27 parsing fixed : small condition in parseCommand changed.
  includes/Server.hpp
  srcs/Client.cpp
  srcs/Server.cpp
  srcs/main.cpp
  srcs/parsing.cpp
Labels: bug

#29 Fix reference problems
  includes/Channel.hpp
  includes/Commands.hpp
  includes/Numerical_replies.hpp
  srcs/Channel.cpp
  srcs/commands/invite.cpp
  srcs/commands/list.cpp
  srcs/commands/nick.cpp
  srcs/commands/ping.cpp
  srcs/commands/topic.cpp
  srcs/utils.cpp
Labels: bug

#31 Mdp command
  includes/Client.hpp
  includes/Numerical_replies.hpp
  includes/Server.hpp
  srcs/Client.cpp
  srcs/Server.cpp
  srcs/commands/pass.cpp
  srcs/commands/ping.cpp
  srcs/main.cpp
  srcs/parsing.cpp
Labels: bug

#33 Fixed infinite loop
  includes/Server.hpp
  srcs/ManageServer.cpp
  srcs/Server.cpp
Labels: bug

#34 [JOIN] v2
  includes/Numerical_replies.hpp
  srcs/ManageServer.cpp
  srcs/commands/join.cpp
  srcs/commands/topic.cpp
Labels: enhancement

#39 New feature : Part command
  Makefile
  includes/Commands.hpp
  includes/Numerical_replies.hpp
  srcs/ManageServer.cpp
  srcs/Server.cpp
  srcs/commands/join.cpp
  srcs/commands/list.cpp
  srcs/commands/names.cpp
  srcs/commands/nick.cpp
  srcs/commands/part.cpp
  srcs/utils.cpp
Labels: enhancement

#40 [Fix] Nickname already used
  includes/Commands.hpp
  includes/Numerical_replies.hpp
  srcs/Server.cpp
  srcs/commands/join.cpp
  srcs/commands/nick.cpp
  srcs/commands/part.cpp
Labels: bug

#46 [QUIT] [VALGRIND] SIGPIPE when client quits
  Makefile
  includes/Commands.hpp
  srcs/ManageServer.cpp
  srcs/Server.cpp
  srcs/commands/oper.cpp
  srcs/commands/quit.cpp
Labels: bug

#48 [CMD] Implement OPER
  .gitignore
  includes/Numerical_replies.hpp
  includes/Server.hpp
  srcs/Server.cpp
  srcs/commands/oper.cpp
  srcs/config/ManageServOperators.config
  srcs/main.cpp
Labels: enhancement

#50 [Fix] Channel changes by one user are updated for all the others
  includes/Numerical_replies.hpp
  srcs/commands/join.cpp
  srcs/commands/topic.cpp
Labels: bug, enhancement

#51 [SIGNALS] Managing the CTRL+C,D and Z
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  Makefile
  includes/Client.hpp
  includes/Commands.hpp
  includes/Irc.hpp
  includes/Macro.hpp
  includes/Numerical_replies.hpp
  includes/Server.hpp
  srcs/ManageServer.cpp
  srcs/ManageServerUtils.cpp
  srcs/class/Channel.cpp
  srcs/class/Client.cpp
  srcs/class/Server.cpp
  srcs/commands/ban.cpp
  srcs/commands/invite.cpp
  srcs/commands/join.cpp
  srcs/commands/kick.cpp
  srcs/commands/list.cpp
  srcs/commands/names.cpp
  srcs/commands/nick.cpp
  srcs/commands/notice.cpp
  srcs/commands/oper.cpp
  srcs/commands/part.cpp
  srcs/commands/pass.cpp
  srcs/commands/ping.cpp
  srcs/commands/privmsg.cpp
  srcs/commands/quit.cpp
  srcs/commands/topic.cpp
  srcs/commands/unban.cpp
  srcs/main.cpp
  srcs/parsing.cpp
  srcs/utils.cpp
Labels: bug, enhancement

#62 [NICK] [USER] Improved parsing (error handling)
  Makefile
  doc_irc/pseudo_code.hpp
  includes/Client.hpp
  includes/Commands.hpp
  includes/Numerical_replies.hpp
  srcs/ManageServer.cpp
  srcs/ManageServerUtils.cpp
  srcs/class/Client.cpp
  srcs/class/Server.cpp
  srcs/commands/nick.cpp
  srcs/commands/user.cpp
  srcs/parsing.cpp
Labels: bug

#63 [KILL] cmd done
  Makefile
  includes/Commands.hpp
  includes/Numerical_replies.hpp
  srcs/class/Server.cpp
  srcs/commands/kill.cpp
  srcs/commands/quit.cpp
  srcs/parsing.cpp
  srcs/utils.cpp
Labels: enhancement

#66 Add /mode command
  Makefile
  includes/Channel.hpp
  includes/Client.hpp
  includes/Commands.hpp
  includes/Numerical_replies.hpp
  srcs/class/Channel.cpp
  srcs/class/Client.cpp
  srcs/class/Server.cpp
  srcs/commands/join.cpp
  srcs/commands/kill.cpp
  srcs/commands/list.cpp
  srcs/commands/mode.cpp
  srcs/commands/names.cpp
  srcs/commands/oper.cpp
  srcs/commands/topic.cpp
  srcs/utils.cpp
Labels: enhancement

#67 [Feat] Added required RPL of welcome when client successfully registered
  includes/Irc.hpp
  includes/Numerical_replies.hpp
  includes/Server.hpp
  srcs/class/Server.cpp
  srcs/main.cpp
Labels: enhancement

#68 [REGISTRATION] NICK and PASS
  srcs/ManageServer.cpp
  srcs/class/Server.cpp
  srcs/commands/nick.cpp
  srcs/commands/pass.cpp
  srcs/utils.cpp
Labels: bug

#73 [REGISTER] Error handling improved in both irssi and nc
  includes/Client.hpp
  srcs/ManageServer.cpp
  srcs/class/Client.cpp
  srcs/class/Server.cpp
  srcs/commands/nick.cpp
  srcs/commands/pass.cpp
  srcs/commands/user.cpp
Labels: bug

#77 [CMD PARSING]
  srcs/ManageServer.cpp
  srcs/ManageServerUtils.cpp
  srcs/class/Client.cpp
  srcs/class/Server.cpp
  srcs/commands/invite.cpp
  srcs/commands/kick.cpp
  srcs/commands/names.cpp
  srcs/commands/part.cpp
  srcs/commands/pass.cpp
  srcs/commands/quit.cpp
  srcs/parsing.cpp
Labels: bug

#78 [MOTD] Command
  Makefile
  includes/Commands.hpp
  includes/Numerical_replies.hpp
  includes/Server.hpp
  srcs/class/Server.cpp
  srcs/commands/motd.cpp
  srcs/config/motd.config
  srcs/parsing.cpp
  srcs/utils.cpp
Labels: enhancement

#71 Fix privmsg & notice
  includes/Numerical_replies.hpp
  srcs/commands/notice.cpp
  srcs/commands/privmsg.cpp
Labels: bug
